# Generated by Django 3.0.11 on 2020-12-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0007_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='phone',
        ),
    ]
