# Generated by Django 3.0.11 on 2020-12-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0008_auto_20201223_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(),
        ),
    ]
