# Generated by Django 3.0.11 on 2020-12-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0009_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(),
        ),
    ]
