# Generated by Django 3.0.11 on 2020-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0013_auto_20201227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
    ]
