# Generated by Django 3.0.11 on 2020-12-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0014_orderupdate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('descr', models.CharField(max_length=500)),
            ],
        ),
    ]
