# Generated by Django 3.0.11 on 2021-01-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SabjiAtHome', '0016_ordersbth_ordersmth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordersbth',
        ),
        migrations.DeleteModel(
            name='Ordersmth',
        ),
    ]
